name: Mickey
favicon: null
layout_spectrum: 0.76405
typography_spectrum: 0.21669
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4b74bf'
    - '#8dc6f1'
    - '#010302'
    - '#e5ecfd'
    - '#bf645e'
  brandStrength: 0.8125
  lightness: 0.875
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
